/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import controladores.ControladorCarpa;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import modelos.Carpa;

/**
 *
 * @author LENOVO
 */
public class VentanaBotones extends javax.swing.JFrame implements ActionListener {

    JButton[][] botones;
    private ControladorCarpa controlador;

    /**
     * Creates new form VentanaCarpas
     */
    public VentanaBotones() {
        initComponents();
        setLocationRelativeTo(this);
        botones = new JButton[3][6];
        controlador = new ControladorCarpa();
        cargarBotones();
        validarPosiciones();
    }

    public void cargarBotones() {
        int ancho = 45;
        int alto = 45;
        int texto = 1;
        for (int i = 0; i < botones.length; i++) {
            for (int j = 0; j < botones[i].length; j++) {
                botones[i][j] = new JButton();
                int separadoX = (j > 1) ? 40 : 20;
                separadoX = (j > 3) ? 70 : separadoX;
                
                
                int separadoY = (i > 0) ? 30 : 20;
                separadoY = (i > 1) ? 40 : separadoY;
                
                botones[i][j].setBounds(
                        (j * ancho + separadoX),
                        (i * alto + separadoY),
                        ancho, alto);
                botones[i][j].setText(String.valueOf(texto));
                botones[i][j].addActionListener(this);
                panelCarpas.add(botones[i][j]);
                texto++;
            }
        }

    }

    public void validarPosiciones() {
        for (int i = 0; i < botones.length; i++) {
            for (int j = 0; j < botones[i].length; j++) {
                Carpa carpa = controlador.obtenerCarpa(i, j);
                if (carpa.getEstado().equals(Carpa.DISPONIBLE)) {
                    botones[i][j].setBackground(Color.WHITE);
                } else if (carpa.getEstado().equals(Carpa.OCUPADA)) {
                    botones[i][j].setBackground(Color.BLUE);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCarpas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelCarpas.setBackground(new java.awt.Color(255, 255, 255));
        panelCarpas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCarpasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelCarpasLayout = new javax.swing.GroupLayout(panelCarpas);
        panelCarpas.setLayout(panelCarpasLayout);
        panelCarpasLayout.setHorizontalGroup(
            panelCarpasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );
        panelCarpasLayout.setVerticalGroup(
            panelCarpasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 253, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCarpas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCarpas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelCarpasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCarpasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panelCarpasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaBotones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaBotones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaBotones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaBotones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaBotones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelCarpas;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        for (int i = 0; i < botones.length; i++) {
            for (int j = 0; j < botones[i].length; j++) {
                if (e.getSource().equals(botones[i][j])) {
                    Carpa carpa = controlador.obtenerCarpa(i, j);
                    if (carpa.getEstado().equals(Carpa.DISPONIBLE)) {
                        VentanaRegistro ventana = new VentanaRegistro(carpa);
                        ventana.setVisible(true);
                        this.dispose();
                    } else if (carpa.getEstado().equals(Carpa.OCUPADA)) {
                        VentanaInfo ventana = new VentanaInfo(carpa);
                        ventana.setVisible(true);
                        this.dispose();

                    }
                }
            }
        }
    }
}
